### ISSUE TITLE
Expose errors when parsing CSS

### ISSUE THREAD

**Issue by athyuttamre** [Quramy/typed-css-modules#10]
Right now the module silently fails with the `.create` Promise not returning when there are errors. When used with webpack this holds up the build process because webpack waits for the Promise to return before moving on to other steps.

Could you expose any errors through the API please?

**Comment by Quramy** [comment]
@athyuttamre .

Sorry, it's a bug... I'll fix it.

**Comment by athyuttamre** [comment]
Thank you! Could you also take a look at #7 please?
