### ISSUE TITLE
tslint: file should end with a newline

### ISSUE THREAD

**Issue by avanderhoorn** [Quramy/typed-css-modules#11]
With the linting rules that we have setup, tslint wants us to end things with a newline. Any chance a config option could be added for those who need/want to end things with a newline?

**Comment by Quramy** [comment]
Hi @avanderhoorn . I add `os.EOL` when writing .d.ts files(see the above commit). Please check out it.

**Comment by avanderhoorn** [comment]
Works great. Huge thanks!!!
