### ISSUE TITLE
Please add to the README.md that we should use .module.css

### ISSUE THREAD

**Issue by amhoba2014** [Quramy/typed-css-modules#193]
I have used the CRA default `.css` files and this library had no effect.  
Switching to `.module.css` made it working.

So please add this note to the README.md thanks.

**Comment by grbd** [comment]
I've noticed the convention of using .module.css is one used by the vite build system.
I think for webpack it's not mandatory. So it may depend on which build system is in use and how it's configured.
That being said it wouldn't hurt for something to be in the readme about it
