### ISSUE TITLE
Support TypeScript option `allowArbitraryExtensions`

### ISSUE THREAD

**Issue by esdmr** [Quramy/typed-css-modules#222]
Since TypeScript 5.0, there is a new option called [`allowArbitraryExtensions`](https://www.typescriptlang.org/tsconfig#allowArbitraryExtensions) which allows any file to have a declaration file and be imported, without needing to add an additional `.js` extension, which was previously required by TypeScript under some configurations.

Unfortunately, `allowArbitraryExtensions` does not use `file.ext.d.ts`. It uses `file.d.ext.ts`. This means that this project does not currently work with this option yet.

I am currently working around this in [esdmr/rte/vite/typed-css-modules.ts](https://github.com/esdmr/rte/blob/main/vite/typed-css-modules.ts#L37L45)

> ```js
> Object.defineProperty(content, 'outputFileName', {
>     get() {
>         return this.rInputPath.replace(/\.css$/, '') + '.d.css.ts';
>     },
> });
> ```

**Comment by esdmr** [comment]
Seems to be resolved via #277 :tada:

**Comment by jfurfaro** [comment]
@esdmr note that you'll need v0.9.1 to use the CLI option, as #277 I accidentally forgot to map it during the run command. #291 fixes that
