### ISSUE TITLE
Missing Contribution.md

### ISSUE THREAD

**Issue by Parth4git** [Quramy/typed-css-modules#230]
Problem or desire
The repository looks incomplete because of the missing CONTRIBUTING.md file to specify the rules and regulations to follow while contributing to the repository, I want to add that file to the repo.

Proposal
Add the CONTRIBUTING file to the repository with guidelines.

Kindly assign me this issue. @Quramy

**Comment by Parth4git** [comment]
@Quramy Kindly reply to my issue

**Comment by Quramy** [comment]
You’re welcome to open PR about the CONTRIBUTING.md
