### ISSUE TITLE
Excluding pattern

### ISSUE THREAD

**Issue by zunder** [Quramy/typed-css-modules#34]
Is there any way to exclude files from the search? I tried:

```
tcm -p src/**/(!*.global)*.css
```
But it does not seem to work.

**Comment by Quramy** [comment]
https://github.com/isaacs/node-glob is used to expand glob patterns. The node-glob syntax is available.

**Comment by zunder** [comment]
According to node-glob that pattern should work:
```
tcm -p src/**/*!(.global).less
```
But it yields an error. I can not tell if it is an error on node-glob's side, but according to the docs, the above pattern should work.

**Comment by Quramy** [comment]
It seems that the above pattern `src/**/*!(.global).less` matches files like `foo.global.less` with node-glob :thinking: . I don't know it's in spec or a bug, but I found `src/**/!(*.global).less` excludes global less files. And this pattern also works with `tcm -p`. Please try it :)

```sh
mkdir -p src
touch src/common1.global.css
touch src/common2.global.css
touch src/main.css
npm init -f
npm install glob

cat << JS | node
const glob = require("glob");

console.log(glob.sync('src/**/*!(.global).css'));
// [ 'src/common1.global.css', 'src/common2.global.css', 'src/main.css' ]

console.log(glob.sync('src/**/!(*.global).css'));
// [ 'src/main.css' ]
JS
```

**Comment by zunder** [comment]
Starting tcm through the npm 5.0.0 yields following:
```
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `tcm -p src/**/!(*.global).less'
```
`tcm -p src/**/*.less` on the other hand works fine.

As a workaround I just use js and tcm API:
```js
const DtsCreator = require('typed-css-modules')
const glob = require("glob")

const creator = new DtsCreator()
 
glob.sync('src/**/!(*.global).less').forEach(path =>
    creator.create(path).then(content => {
        content.messageList.forEach(msg => console.log(msg))
        content.writeFile()
        console.log(content.outputFilePath)
    })
)
```

I guess that is good enough for my purposes. This issue can be closed if you don't want to investigate on the usage without API.

**Comment by Quramy** [comment]
> `sh: -c: line 0: syntax error near unexpected token ('`

Did you escape command ?  The pattern includes meta character `(`.

Please try with double quotation :

```sh
tcm -p "src/**/!(*.global).less"
```

**Comment by zunder** [comment]
That one was to obvious to try out. 😬
Thank you for your help, works perfectly fine now!
