### ISSUE TITLE
Feature request: Add content parameter to DtsCreator.create

### ISSUE THREAD

**Issue by andersekdahl** [Quramy/typed-css-modules#5]
We use Webpack to build our css and we want to use `typed-css-modules` to create type definitions for it. But we also use scss and `typed-css-modules` fails on scss specific syntax which makes this promise fail: https://github.com/Quramy/typed-css-modules/blob/master/src/dtsCreator.js#L94 with a `CssSyntaxError` and `Unknown word` for thinks like `max-height: #{$base-line-height * $line-count}rem;`.

When we call `DtsCreator.create()` we have both the path to the file, and the contents of the file transformed from scss to css. We'd like to be able to pass a second argument to `DtsCreator.create()` with the contents of the file and not have `typed-css-modules` read it from the file since it contains invalid css syntax.

Btw, thanks for a great module!

**Comment by Quramy** [comment]
@andersekdahl . I got what you want. And I don't know how do I add implement this feature. I come up with the following options:

1. Re-implement this feature as some post-css plugin. post-css ecosystem has SASS parse and css modules plugin. But I'm not familier with post-css's plugin development...
2. Add feature to input from stream pipe which is created by lib-sass for example.

Do you have any idea ?

**Comment by andersekdahl** [comment]
For our use case you don't have to care about sass at all. The only thing we need is to be able to pass in the contents of the file passed to `DtsCreator.create()`. That is, instead of just passing in the path and having `typed-css-modules` read the contents of the file, we pass the path and the contents and `typed-css-modules` will just use that content to parse instead of reading the file.

**Comment by Quramy** [comment]
https://github.com/Quramy/typed-css-modules/commit/a855de4b3f1514c4780a677f87531449531cb5aa#diff-04c6e90faac2675aa89e2176d2eec7d8R115

How about this?

**Comment by andersekdahl** [comment]
Haven't tested it, but it looks exactly like what we want!

**Comment by andersekdahl** [comment]
Tried it now, works like a charm! Thank you!

**Comment by skovy** [comment]
I also recently ran into this but was hoping to still use it as a CLI. If you're looking to support SASS consider looking at [`typed-scss-modules`](https://www.npmjs.com/package/typed-scss-modules) as well 👍
