### ISSUE TITLE
Use `os.EOL` instead of `\n`

### ISSUE THREAD

**Issue by andersekdahl** [Quramy/typed-css-modules#6]
This line:
https://github.com/Quramy/typed-css-modules/blob/master/src/dtsCreator.js#L40

explicitly uses `\n` instead of `require('os').EOL` which makes all * .d.ts files show up as modified for us.

Could you change it to `require('os').EOL` instead?

**Comment by Quramy** [comment]
Ok, please wait a minute...

**Comment by Quramy** [comment]
Please check it out ;)

**Comment by andersekdahl** [comment]
Works great, thanks! And thanks for your super fast replies!
