### ISSUE TITLE
The TypeScript typing is not compatible with ES import syntax

### ISSUE THREAD

**Issue by pyrocat101** [Quramy/typed-css-modules#76]
In the distributed `.d.ts`, the `DtsCreator` is exported via `export =`, which is incompatible with the standard ES import syntax. The consumer of the library needs to import via TypeScript specific `import DtsCreator = require('typed-css-modules')`.

**Comment by gdelmas** [comment]
this is covered in #75 

https://github.com/Quramy/typed-css-modules/pull/75/files#diff-f41e9d04a45c83f3b6f6e630f10117feR1

**Comment by pyrocat101** [comment]
@gdelmas awesome :)
