### ISSUE TITLE
quoted identifers

### ISSUE THREAD

**Issue by broomstick73** [Quramy/typed-css-modules#77]
I'm using typed-css-modules-webpack-plugin in a couple projects and it's actually using typed-css-modules to create .css.d.ts files. The issue is that one of the projects produces non-quoted-identifers while the other project produces quoted identifiers and I haven't found what is telling it which way to create them. Is it a setting in a file somewhere?
Example one might create:
```
declare const styles: {
  readonly "linkStyle": string;
};
export = styles;
```
while the other will not have the quotes. Any idea?

**Comment by rfgamaral** [comment]
Maybe not all projects use the same `typed-css-modules` version?

**Comment by broomstick73** [comment]
Yes, this was exactly the issue.
