### ISSUE TITLE
Synchronously create files

### ISSUE THREAD

**Issue by athyuttamre** [Quramy/typed-css-modules#8]
Is there a way to synchronously create the .d.ts files? I'm using this module with webpack and need to generate these files before I run the TypeScript compiler.

**Comment by athyuttamre** [comment]
Hmm, never mind, even synchronously creating files doesn't seem to be fixing my issue (I hardcoded the output and tried it out.) Would be nice to have the option though!

**Comment by AlexGalays** [comment]
That is indeed surprising.

The example invokes typed-css-modules immediately followed by tsc. That will often fail won't it ?

**Comment by athyuttamre** [comment]
@AlexGalays that's correct. What's happening is:

- Webpack reads the filesystem, and makes an in memory cache of the changed files.
- typed-css-modules-loader uses this cache and generates the .d.ts files.
- tsc uses this cache and compiles the TypeScript files. At this point the new .d.ts files are not in the cache, so tsc doesn't recognize them and throws errors.

The next time webpack runs, it reads the filesystem again, and this time the .d.ts files are included. This way tsc compiles correctly without errors.

For more discussion, see this issue: https://github.com/Quramy/typed-css-modules/issues/2.

Closing for now because synchronous creation isn't that useful unless we can update the webpack cache before tsc uses it.

**Comment by AlexGalays** [comment]
@athyuttamre  Thanks for the loader lead. 
The other discussion is a bit confusing. Do you advocate the plugin or the loader (I assume the loader, which I too would prefer) 
Is there an npm package with a fully working loader?

Cheers

Cheers

**Comment by AlexGalays** [comment]
is there no way to create the .d.ts files around the same time the JS bundle is rewritten ? As it stands, my app is recompiled twice for every change so I reverted to untyped css modules for now.

**Comment by athyuttamre** [comment]
That's our experience too. There is an emitFile API in the Webpack loader docs, but I never got it to work. Perhaps someone with more experience could look into it.

**Comment by AlexGalays** [comment]
Is this fixed by any chance? css modules are the last untyped bit in our whole app.
