### ISSUE TITLE
Package maintenance

### ISSUE THREAD

**Issue by LucaColonnello** [Quramy/typed-css-modules#99]
Is this package still maintained?

I wanted to contribute but I can see many contributions to other issues with PRs from Jun 2020 not yet merged :)

If it's still maintained, I'd like to file a PR to solve the named exports issue, as it currently does not support named exports (although it used to in version 0.4).

**Comment by Quramy** [comment]
Thanks, PRs are welcome.

> as it currently does not support named exports (although it used to in version 0.4).

Hmmm. I can't remember the reason for that change. 🤔

**Comment by LucaColonnello** [comment]
Thank you for your reply, I think I have a PR already (almost) :D

Not sure why, but it's clear to me that we need both, as named exports changes the way you import the style, so there cannot be a unique way to make it work for both if we want to enable tree shaking :)

**Comment by LucaColonnello** [comment]
I've opened the [PR now](https://github.com/Quramy/typed-css-modules/pull/100), will appreciate if someone could review and if ok merge it. Please do let me know if anything is wrong, I'll make time to correct it. 🙏 

I also added tests 🥇

**Comment by LucaColonnello** [comment]
@Quramy Thank you for publishing my changes so fast, appreciate I'm a new contributor 🙏
